<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup Label="Project References">
    <ProjectReference Include="..\fluXis\fluXis.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
  </ItemGroup>
</Project>
