name: Bug report
description: Create a report to help us improve the game.
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Is this a new issue?
      description: Please check the other issues if this was already reported.
      options:
        - label: Yes, I checked the other issues.
          required: true
  - type: textarea
    attributes:
      label: fluXis version
      description: What version of fluXis are you using? (Visible on the first page of the settings menu)
      value: |
        - fluXis version:
      render: Markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Device
      description: What device are you using? (Windows 10, Windows 11, etc.)
      value: |
        - Device:
      render: Markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description of the bug
      description: What exactly is happening?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: What should have happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the bug?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots/Video
      description: If applicable, add screenshots or a video to help explain your problem.
    validations:
      required: true
