using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using fluXis.Audio.FFT.Serialization;
using fluXis.Audio.FFT.Structures.Cache;
using fluXis.Audio.FFT.Structures.Data;
using fluXis.Database;
using fluXis.Database.Maps;
using JetBrains.Annotations;
using ManagedBass;
using osu.Framework.Allocation;
using osu.Framework.Audio.Callbacks;
using osu.Framework.Graphics;
using osu.Framework.Logging;
using osu.Framework.Platform;
using osu.Framework.Utils;

namespace fluXis.Audio.FFT;

/// <summary>
/// An FFT Data provider differs from <see cref="osu.Framework.Audio.Track.Waveform"/> in that it provides full frequency data that can be cached in-memory (<see cref="FFTCache"/>) &amp; on disk.
/// </summary>
public partial class AudioAnalyzer : Component
{
    /// <summary>
    /// The sample interval between bands in ms.
    /// </summary>
    public const uint RESOLUTION = 20;

    /// <summary>
    /// Maximum number of audio caches to keep in memory at once.
    /// </summary>
    private const int max_cached = 10;

    /// <summary>
    /// FFT512 gives ~93.75hz accuracy.
    /// </summary>
    private const DataFlags fft_samples = DataFlags.FFT512;

    /// <summary>
    /// Number of bins generated by the FFT. Must correspond to <see cref="fft_samples"/>.
    /// </summary>
    public const int FFT_BINS = 256;

    /// <summary>
    /// The actual frame size which includes bins + low, mid, high and total bands.
    /// </summary>
    public const int FRAME_SIZE = FFT_BINS + 4;

    /// <summary>
    /// Minimum frequency for low-range (bass) frequencies. Based on lower range of bass drum fallout.
    /// </summary>
    private const float low_min = 20;

    /// <summary>
    /// Minimum frequency for mid-range frequencies. Based on higher range of bass drum fallout.
    /// </summary>
    private const float mid_min = 100;

    /// <summary>
    /// Minimum frequency for high-range (treble) frequencies.
    /// </summary>
    private const float high_min = 2000;

    /// <summary>
    /// Maximum frequency for high-range (treble) frequencies. A sane value.
    /// </summary>
    private const float high_max = 12000;

    public int SampleRate => channelInfo.Frequency;

    [Resolved]
    private GameHost host { get; set; }

    public Guid ID { get; private set; }
    public string AudioFileName { get; private set; }
    public string AudioHash { get; private set; }

    public Task ComputeComplete { get; private set; } = Task.CompletedTask;

    private CancellationTokenSource cancelSource = new();

    private Storage cacheStorage => host.CacheStorage.GetStorageForDirectory(FluXisGame.FFT_CACHE_PATH);

    private readonly Dictionary<string, FFTCache> caches = new();
    private readonly LinkedList<string> lru = new();

    private FFTCache currentCache { get; set; }

    private Stream stream;
    private FileCallbacks fileCallbacks;
    private int decodeStreamHandle;
    private ChannelInfo channelInfo;
    public long ChannelLength { get; private set; }
    private bool isReady;

    private FFTCache getOrCreateCache(string hash)
    {
        if (caches.TryGetValue(hash, out var existing))
        {
            lru.Remove(hash);
            lru.AddFirst(hash);
            return existing;
        }

        if (caches.Count >= max_cached)
        {
            string lruKey = lru.Last!.Value;
            lru.RemoveLast();
            caches[lruKey].Dispose();
            caches.Remove(lruKey);
        }

        var cache = tryLoadCacheFromDisk(hash) ?? new FFTCache { Hash = hash };
        caches[hash] = cache;
        lru.AddFirst(hash);

        return cache;
    }

    public virtual void SetAudio(RealmMap map)
    {
        if (map is null) return;
        if (!map.EnableVisualization) return;

        string fullAudioPath = MapFiles.GetFullPath(map.FullAudioPath);

        if (!File.Exists(fullAudioPath)) return;

        Stream audioStream = File.OpenRead(fullAudioPath);

        SetAudio(
            audioStream,
            map.MapSet.ID,
            map.Metadata.Audio,
            map.AudioHash
        );
    }

    public virtual void SetAudio([CanBeNull] Stream newStream, Guid cacheId, string fileName, string audioHash)
    {
        if (audioHash != null && AudioHash != null && audioHash == AudioHash)
            return;

        cancelSource.Cancel();
        cancelSource = new CancellationTokenSource();
        var token = cancelSource.Token;

        isReady = false;

        AudioFileName = fileName;
        AudioHash = audioHash;
        ID = cacheId;

        currentCache = audioHash != null ? getOrCreateCache(audioHash) : null;

        if (decodeStreamHandle != 0)
        {
            Bass.StreamFree(decodeStreamHandle);
            decodeStreamHandle = 0;
        }

        fileCallbacks?.Dispose();
        stream?.Dispose();
        stream = newStream;

        if (stream == null)
            return;

        if (Bass.CurrentDevice < 0)
        {
            Logger.Log("No bass device is available to get fft data.");
            return;
        }

        fileCallbacks = new FileCallbacks(new DataStreamFileProcedures(stream));
        decodeStreamHandle = Bass.CreateStream(StreamSystem.NoBuffer, BassFlags.Decode | BassFlags.Float, fileCallbacks.Callbacks, fileCallbacks.Handle);

        if (decodeStreamHandle == 0)
        {
            LogBassError("could not create stream");
            return;
        }

        if (!Bass.ChannelGetInfo(decodeStreamHandle, out ChannelInfo info))
        {
            LogBassError("could not retrieve channel information");
            return;
        }

        channelInfo = info;
        ChannelLength = Bass.ChannelGetLength(decodeStreamHandle);

        if (ChannelLength < 0)
        {
            LogBassError("could not retrieve channel length");
            return;
        }

        isReady = true;

        ComputeComplete = Task.Run(() => precomputeFullTrack(token), token);
    }

    private void precomputeFullTrack(CancellationToken token = default)
    {
        if (!isReady || currentCache == null) return;

        double lengthMs = Bass.ChannelBytes2Seconds(decodeStreamHandle, ChannelLength) * 1000.0;
        uint totalTime = (uint)Math.Ceiling(lengthMs / RESOLUTION) * RESOLUTION + RESOLUTION;

        currentCache.ContainsAndAllocate(0, totalTime, out var missing);

        foreach (var range in missing)
        {
            token.ThrowIfCancellationRequested();
            ComputeRange(range);
        }

        SaveCacheToDisk();

        Logger.Log($"FFT Full track cached for {AudioFileName}, mapSetID: {ID}.");
    }

    public virtual FFTFrame[] GetAmplitudes(
        int tStart,
        int tEnd,
        int interval,
        int binCount = FFT_BINS,
        FFTProcessor processor = null
    )
    {
        if (!isReady || currentCache == null)
            return [];

        var cache = currentCache;

        // extra pad just in case it ever goes out of bounds
        cache.ContainsAndAllocate((uint)Math.Max(tStart, 0), (uint)Math.Max(tEnd, 0) + RESOLUTION, out var missing);

        var frames = cache.GetFrames(tStart, tEnd, interval);

        if (processor != null)
            frames = processor.Process(frames);

        if (binCount == FFT_BINS)
            return frames;

        return frames.Select(frame => new FFTFrame(
            resizeArray(frame.Amplitudes, binCount),
            frame.Bands
        )).ToArray();
    }

    private static float[] resizeArray(float[] data, int newSize)
    {
        if (data.Length == newSize) return data;

        var result = new float[newSize];
        float ratio = (float)data.Length / newSize;

        for (int i = 0; i < newSize; i++)
        {
            float position = i * ratio;
            int index1 = (int)position;
            int index2 = Math.Min(index1 + 1, data.Length - 1);
            float fraction = position - index1;

            result[i] = (float)Interpolation.Lerp(data[index1], data[index2], fraction);
        }

        return result;
    }

    protected virtual void ComputeRange([In, Out] FFTRange range)
    {
        float[] bins = new float[FFT_BINS];

        for (int frame = 0; frame < range.FrameCount; frame++)
        {
            double timeSec = (range.TStart + frame * RESOLUTION) / 1000.0;
            long pos = Bass.ChannelSeconds2Bytes(decodeStreamHandle, timeSec);
            Bass.ChannelSetPosition(decodeStreamHandle, pos, PositionFlags.Bytes);

            int length = Bass.ChannelGetData(decodeStreamHandle, bins, (int)fft_samples);

            if (length < 0 && Bass.LastError != Errors.Ended)
            {
                LogBassError("could not retrieve FFT data");
                return;
            }

            int offset = frame * FRAME_SIZE;

            for (int i = 0; i < FFT_BINS; i++)
            {
                float weight = 1.0f + ((float)i / FFT_BINS) * 15.0f;
                float weightedValue = bins[i] * weight;

                float scaled = MathF.Sqrt(weightedValue) * 1.5f;

                range.Data[offset + i] = floatToByte(scaled);
            }

            range.Data[offset + FFT_BINS + 0] = floatToByte(computeIntensity(channelInfo, bins, low_min, mid_min));
            range.Data[offset + FFT_BINS + 1] = floatToByte(computeIntensity(channelInfo, bins, mid_min, high_min));
            range.Data[offset + FFT_BINS + 2] = floatToByte(computeIntensity(channelInfo, bins, high_min, high_max));
            range.Data[offset + FFT_BINS + 3] = floatToByte(computeTotalIntensity(bins));
        }
    }

    private static byte floatToByte(float value) =>
        (byte)(Math.Clamp(value, 0f, 1f) * 255f);

    private static float computeIntensity(ChannelInfo info, float[] bins, float startFrequency, float endFrequency)
    {
        int startBin = (int)(FFT_BINS * 2 * startFrequency / info.Frequency);
        int endBin = (int)(FFT_BINS * 2 * endFrequency / info.Frequency);

        startBin = Math.Clamp(startBin, 0, bins.Length);
        endBin = Math.Clamp(endBin, 0, bins.Length);

        if (startBin == endBin)
            endBin = Math.Min(startBin + 1, bins.Length);

        if (startBin >= endBin) return 0;

        float sum = 0;

        for (int i = startBin; i < endBin; i++)
        {
            float weight = 1.0f + ((float)i / FFT_BINS) * 15.0f;
            sum += bins[i] * weight;
        }

        return MathF.Sqrt(sum / (endBin - startBin)) * 1.5f;
    }

    private static float computeTotalIntensity(float[] bins)
    {
        float sum = 0;

        for (int i = 0; i < FFT_BINS; i++)
        {
            float weight = 1.0f + ((float)i / FFT_BINS) * 15.0f;
            sum += bins[i] * weight;
        }

        return MathF.Sqrt(sum / FFT_BINS) * 1.5f;
    }

    private FFTCache tryLoadCacheFromDisk(string hash)
    {
        if (!cacheStorage.Exists(hash))
            return null;

        try
        {
            byte[] data;

            using (var fileStream = cacheStorage.GetStream(hash))
            {
                data = new byte[fileStream.Length];
                fileStream.ReadExactly(data);
            }

            var deserializer = new FFTDeserializer(data);
            var info = deserializer.GetInfo();

            if (info.Hash != hash)
            {
                Logger.Log($"FFT cache hash mismatch for {hash}, discarding.");
                cacheStorage.Delete(hash);
                return null;
            }

            var cache = deserializer.Deserialize();
            Logger.Log($"FFT cache loaded from disk for {hash}, mapSetID: {ID}.");
            return cache;
        }
        catch (Exception e)
        {
            Logger.Log($"Failed to load FFT cache for {hash}: {e.Message}");
            cacheStorage.Delete(hash);
            return null;
        }
    }

    public void SaveCacheToDisk()
    {
        if (currentCache == null) return;

        try
        {
            byte[] data = new FFTSerializer(currentCache).Serialize();
            string filename = currentCache.Hash;

            using var fileStream = cacheStorage.GetStream(filename, FileAccess.Write, FileMode.Create);
            fileStream.Write(data);

            Logger.Log($"FFT cache saved to disk for {AudioFileName}, mapSetID: {ID}.");
        }
        catch (Exception e)
        {
            Logger.Log($"Failed to save FFT cache for {AudioFileName}: {e.Message}");
        }
    }

    protected static void LogBassError(string reason) =>
        Logger.Log($"BASS failure in {nameof(AudioAnalyzer)}: {reason} ({Bass.LastError})");

    protected override void Dispose(bool isDisposing)
    {
        base.Dispose(isDisposing);

        if (!isDisposing) return;

        cancelSource.Cancel();
        cancelSource.Dispose();

        foreach (var cache in caches.Values)
            cache.Dispose();

        caches.Clear();
        lru.Clear();

        if (decodeStreamHandle != 0)
            Bass.StreamFree(decodeStreamHandle);

        fileCallbacks?.Dispose();
        stream?.Dispose();
        stream = null;
    }
}
